apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: sajadahmed/auth-service:latest
          ports:
            - containerPort: 3002
          env:
            - name: DATABASE_URL
              value: postgres://postgres:${POSTGRES_PASSWORD}@postgres-svc:5432/microservices
            - name: REDIS_URL
              value: redis://redis-svc:6379
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - port: 80
      targetPort: 3002
