apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing
spec:
  replicas: 2
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
        - name: processing
          image: sajadahmed/processing-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: DATABASE_URL
              value: postgres://postgres:${POSTGRES_PASSWORD}@postgres-svc:5432/microservices
            - name: REDIS_URL
              value: redis://redis-svc:6379
            - name: NODE_ENV
              value: production
---
apiVersion: v1
kind: Service
metadata:
  name: processing-svc
spec:
  type: ClusterIP
  selector:
    app: processing
  ports:
    - port: 80
      targetPort: 3003
